"""initial_schema

Revision ID: 0c54c051309a
Revises: 
Create Date: 2026-04-10 16:54:20.208200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c54c051309a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fen_hash', sa.String(), nullable=False),
    sa.Column('elo_bucket', sa.Integer(), nullable=False),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_cache_fen_hash'), 'opening_cache', ['fen_hash'], unique=False)
    op.create_table('openings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eco_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('starting_moves', sa.JSON(), nullable=False),
    sa.Column('theory_depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openings_eco_code'), 'openings', ['eco_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('guest_token', sa.String(), nullable=True),
    sa.Column('lichess_username', sa.String(), nullable=True),
    sa.Column('target_elo', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('pro_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('target_elo BETWEEN 800 AND 3000', name='ck_user_elo_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_guest_token'), 'users', ['guest_token'], unique=True)
    op.create_index(op.f('ix_users_lichess_username'), 'users', ['lichess_username'], unique=False)
    op.create_table('coach_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('eco_code', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('neon_diagnosis', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_analysis_eco_code'), 'coach_analysis', ['eco_code'], unique=False)
    op.create_index(op.f('ix_coach_analysis_user_id'), 'coach_analysis', ['user_id'], unique=False)
    op.create_table('glitch_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('games_analyzed', sa.Integer(), nullable=False),
    sa.Column('rating_at_generation', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('critical_openings', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('overall_pattern', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glitch_reports_user_id'), 'glitch_reports', ['user_id'], unique=False)
    op.create_table('lichess_games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lichess_game_id', sa.String(), nullable=False),
    sa.Column('eco_code', sa.String(), nullable=True),
    sa.Column('opening_name', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('user_color', sa.String(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('opponent_rating', sa.Integer(), nullable=True),
    sa.Column('pgn', sa.String(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lichess_game_id', name='uq_user_lichess_game')
    )
    op.create_index(op.f('ix_lichess_games_eco_code'), 'lichess_games', ['eco_code'], unique=False)
    op.create_index(op.f('ix_lichess_games_lichess_game_id'), 'lichess_games', ['lichess_game_id'], unique=False)
    op.create_index(op.f('ix_lichess_games_user_id'), 'lichess_games', ['user_id'], unique=False)
    op.create_table('lichess_rating_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('snapshotted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lichess_rating_snapshots_user_id'), 'lichess_rating_snapshots', ['user_id'], unique=False)
    op.create_table('sparring_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opening_id', sa.Uuid(), nullable=True),
    sa.Column('player_color', sa.String(), nullable=False),
    sa.Column('opponent_elo', sa.Integer(), nullable=False),
    sa.Column('current_fen', sa.String(), nullable=False),
    sa.Column('move_history', sa.JSON(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('theory_integrity', sa.Float(), nullable=False),
    sa.Column('theory_exit_move', sa.Integer(), nullable=True),
    sa.Column('session_status', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('excellent_moves', sa.Integer(), nullable=False),
    sa.Column('good_moves', sa.Integer(), nullable=False),
    sa.Column('inaccuracies', sa.Integer(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('blunders', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("session_status IN ('active','completed','abandoned')", name='ck_session_status'),
    sa.CheckConstraint('accuracy_score >= 0 AND accuracy_score <= 100', name='ck_accuracy_range'),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sparring_sessions_user_id'), 'sparring_sessions', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_move_mastery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opening_id', sa.Uuid(), nullable=False),
    sa.Column('move_sequence_hash', sa.String(), nullable=False),
    sa.Column('expected_move', sa.String(), nullable=False),
    sa.Column('fen_before', sa.String(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'move_sequence_hash', name='uq_user_move_hash')
    )
    op.create_index(op.f('ix_user_move_mastery_move_sequence_hash'), 'user_move_mastery', ['move_sequence_hash'], unique=False)
    op.create_index(op.f('ix_user_move_mastery_opening_id'), 'user_move_mastery', ['opening_id'], unique=False)
    op.create_index(op.f('ix_user_move_mastery_user_id'), 'user_move_mastery', ['user_id'], unique=False)
    op.create_table('user_repertoire',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opening_id', sa.Uuid(), nullable=False),
    sa.Column('training_unlocked', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opening_id', name='uq_user_opening')
    )
    op.create_index(op.f('ix_user_repertoire_user_id'), 'user_repertoire', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consecutive_sparring_losses', sa.Integer(), nullable=False),
    sa.Column('last_sparring_loss_at', sa.DateTime(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_repertoire_user_id'), table_name='user_repertoire')
    op.drop_table('user_repertoire')
    op.drop_index(op.f('ix_user_move_mastery_user_id'), table_name='user_move_mastery')
    op.drop_index(op.f('ix_user_move_mastery_opening_id'), table_name='user_move_mastery')
    op.drop_index(op.f('ix_user_move_mastery_move_sequence_hash'), table_name='user_move_mastery')
    op.drop_table('user_move_mastery')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sparring_sessions_user_id'), table_name='sparring_sessions')
    op.drop_table('sparring_sessions')
    op.drop_index(op.f('ix_lichess_rating_snapshots_user_id'), table_name='lichess_rating_snapshots')
    op.drop_table('lichess_rating_snapshots')
    op.drop_index(op.f('ix_lichess_games_user_id'), table_name='lichess_games')
    op.drop_index(op.f('ix_lichess_games_lichess_game_id'), table_name='lichess_games')
    op.drop_index(op.f('ix_lichess_games_eco_code'), table_name='lichess_games')
    op.drop_table('lichess_games')
    op.drop_index(op.f('ix_glitch_reports_user_id'), table_name='glitch_reports')
    op.drop_table('glitch_reports')
    op.drop_index(op.f('ix_coach_analysis_user_id'), table_name='coach_analysis')
    op.drop_index(op.f('ix_coach_analysis_eco_code'), table_name='coach_analysis')
    op.drop_table('coach_analysis')
    op.drop_index(op.f('ix_users_lichess_username'), table_name='users')
    op.drop_index(op.f('ix_users_guest_token'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_openings_eco_code'), table_name='openings')
    op.drop_table('openings')
    op.drop_index(op.f('ix_opening_cache_fen_hash'), table_name='opening_cache')
    op.drop_table('opening_cache')
    # ### end Alembic commands ###
